### ISSUE TITLE
Feature:  Add chinese docs sections

### ISSUE THREAD

**Issue by xiaods** [Conflux-Chain/conflux-developer-site#10]
reason:
We have a large number of Chinese developers who need Chinese language materials for introductory tutorials.

action:
add the Chinese section.

**Comment by xiaods** [comment]
maybe the dropdown section is bug ....

**Comment by xiaods** [comment]
QUESTION: Do we need to display the Chinese and English documents mixed together, or do we need to put a column for the Chinese documents?

**Comment by yqrashawn** [comment]
There're things need to be done before adding multi-language support. Checkout https://github.com/Conflux-Chain/conflux-developer-site/issues/12

**Comment by xiaods** [comment]
close this issue, add comments on #12
