### ISSUE TITLE
Make category section bolder

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/conflux-developer-site#11]
![551586489843_ pic](https://user-images.githubusercontent.com/15090582/78960319-4bda7780-7b20-11ea-9647-7d22851d46ed.jpg)
![651586489982_ pic](https://user-images.githubusercontent.com/15090582/78960324-50069500-7b20-11ea-8e14-8e0cec9a217e.jpg)

**Comment by xiaods** [comment]
OR like Libra Section  effect also accepted.

![WechatIMG225](https://user-images.githubusercontent.com/37678/78960438-aa075a80-7b20-11ea-9ee5-341148921a18.jpeg)

**Comment by xiaods** [comment]
done by core team. please close the issue.
