### ISSUE TITLE
TODO:  Home content needs an update.

### ISSUE THREAD

**Issue by xiaods** [Conflux-Chain/conflux-developer-site#14]
<img width="1190" alt="截屏2020-04-10 下午5 06 37" src="https://user-images.githubusercontent.com/37678/78979145-d1285100-7b4d-11ea-93d1-1c33c22746ec.png">

I found the Home page's content is copy from Docusaurus.  How about updating it asap?  this is not relative about conflux devs.

**Comment by yqrashawn** [comment]
Can be changed here
https://github.com/Conflux-Chain/conflux-developer-site/blob/master/src/pages/index.js#L9

**Comment by xiaods** [comment]
I know the source code's location. but I don't know what content should be replaced here. :-(

**Comment by xiaods** [comment]
Done by core team.
