### ISSUE TITLE
Installation issue in windows platform

### ISSUE THREAD

**Issue by chinajinwanjun** [Conflux-Chain/conflux-developer-site#15]
In windows platform,  execute yarn REINIT will run file reinit.sh, while file *.sh  cannot be executed in windows,  please directly remove this section.

> Installation
> $ yarn REINIT
> $ yarn
> Note: the yarn REINIT command will clear any uncommitted changes under this directory including all submodules in docs folder. It will set everything to the same state as your origin/master.

**Comment by xiaods** [comment]
@chinajinwanjun Oops, the scripts only compatible with linux system. So if you want to support this site, please use WSL feature in windows.

**Comment by xiaods** [comment]
I don't feel currently we need support windows scripts.  this is low priority feature

**Comment by yqrashawn** [comment]
Reflected in the readme file https://github.com/Conflux-Chain/conflux-developer-site/commit/1ad329f357bf64b44101a866f29e153d97dca18f
