### ISSUE TITLE
Cannot fold and unfold navigate bar, missed article navigate bar

### ISSUE THREAD

**Issue by chinajinwanjun** [Conflux-Chain/conflux-developer-site#17]
![Image 2](https://user-images.githubusercontent.com/5502154/79106358-ec40ce00-7da4-11ea-9e3a-22ef02e20a32.png)

**Comment by yqrashawn** [comment]
About collapsible feature. I set it to `false` [here](https://github.com/Conflux-Chain/conflux-developer-site/blob/d3277bf59971cb6b245b239e7f801f9e3da52455/docusaurus.config.js#L15). It's intended.

Confirmed that the per-article nav panel is missing.

Debug info:

It works file in dev env (`yarn start`).
Gone in prod env (`yarn build`)

**Comment by yqrashawn** [comment]
Maybe it's introduced by [this commit](https://github.com/Conflux-Chain/conflux-developer-site/commit/319b2c5) where I introduced remark and rehype plugin into the parser.

**Comment by xiaods** [comment]
@chinajinwanjun how about fix it ?

**Comment by yqrashawn** [comment]
fixed the misssing toc by adding a [custom rehype plugin](https://github.com/Conflux-Chain/conflux-developer-site/blob/master/development/rehype-strip-styles-in-md.js)
