### ISSUE TITLE
REF: newbie question:  对于如何基于浏览器插件钱包开发应用有些疑问

### ISSUE THREAD

**Issue by xiaods** [Conflux-Chain/conflux-developer-site#18]
fyi: https://github.com/Conflux-Chain/conflux-portal/issues/69

**Comment by xiaods** [comment]
根据网友的提议，我觉得一下工作需要做：
1、迁移Conflux Portal的文档到developer site, 我记得有自动导入工具可以做， TBD
2、基于浏览器钱包开发应用的例子是否有 ，这个应该可以帮助开发者引入。 TBD

**Comment by xiaods** [comment]
https://conflux-chain.github.io/conflux-portal-docs/docs/portal/Examples/e2e_test_demo

这个例子的引入过程过于简单，导致开发者应该是不知道如何一行一行的跟着步骤完成案例。

**Comment by xiaods** [comment]
https://github.com/Conflux-Chain/conflux-portal/issues/51

**Comment by xiaozhu001** [comment]
我想在js中获取我钱包中的账户列表，我看官方的例子“const accounts = await conflux.enable()” 是一个数组，但是我在真实操作时，发现数组有且只有一个账户地址，我想将地址列出来，请问如何操作

**Comment by xiaozhu001** [comment]
在下面的这个例子中`
			const amount = 1000000000000000000;
			const amount16 = "0x"+amount.toString(16);
			const txResult = await confluxJS
				.sendTransaction({
				from: accounts[0],
				to: "0x1a2e7a58ec892f254ddfd3a6f1b589782ca29b04",
				value: amount16,
				gas: 21000,
				gasPrice: 10000000000,
				}).confirmed();` 其中的amount是1cfx = 1 * 10^18 GAS

**Comment by xiaozhu001** [comment]
在下面的这个例子中 
`const amount = 1000000000000000000; const amount16 = "0x"+amount.toString(16); const txResult = await confluxJS .sendTransaction({ from: accounts[0], to: "0x1a2e7a58ec892f254ddfd3a6f1b589782ca29b04", value: amount16, gas: 21000, gasPrice: 10000000000, }).confirmed(); `
其中的amount是1cfx = 1 * 10^18 GAS

**Comment by yqrashawn** [comment]
@xiaozhu001 调用 `await conflux.enable()` 会唤起用户授权页面, 返回值仅会包含用户授权的单个账户.

**Comment by xiaods** [comment]
@xiaozhu001 能否提供一份完整的例子，方便后来的朋友学习。

**Comment by xiaozhu001** [comment]
可以的，但是我不会弄到这个上面，我现在实现了基于插件钱包的转账功能，我还在尝试更多的实际项目中会用到的功能场景，我可以提供给你吗？

**Comment by xiaozhu001** [comment]
@yqrashawn  好的，但是这样应该还会有一个断开的接口吧，比如我想使用另一个账号来登录该网站，但是我没有发现关于这个的接口，还有一个问题是我在尝试将资产从账户转到合约账户中，会抛出Out of gas 状态码为-32603的异常。

**Comment by yqrashawn** [comment]
> 但是这样应该还会有一个断开的接口吧

如果用户想换另一个 account 授权这个网站, 可以在 portal 中的 connected sites 中删除掉授权的网站重新进行授权

> 我在尝试将资产从账户转到合约账户中，会抛出Out of gas 状态码为-32603的异常

建议 gas 设置的再高一点

**Comment by xiaozhu001** [comment]
已经ok了，需要在合约中加入交易的（function () payable external，合约0.5.0版本） 函数，合约才能交易。
