### ISSUE TITLE
google chrome 钱包插件问题

### ISSUE THREAD

**Issue by xiaozhu001** [Conflux-Chain/conflux-developer-site#21]
钱包插件问题汇总

**Comment by xiaozhu001** [comment]
![image](https://user-images.githubusercontent.com/31197436/79682269-5a790b00-8253-11ea-9ee6-9de28634057c.png)
如图，我在进行deploy时抛出异常，问题原因是部署的参数修改 由code 改为bytecode confluxJS.Contract({abi: abi,bytecode: code}); 正确使用

**Comment by xiaozhu001** [comment]
目前钱包插件v1.4.0的版本call如何使用？
`let a = await contract.getValue(); console.log(a);`
`function getValue() public view returns(uint256){
        return _value;
    }`


![image](https://user-images.githubusercontent.com/31197436/79682388-6e713c80-8254-11ea-84ec-62a5c622b12c.png)

返回这东西，不知道怎么使用call功能了

**Comment by xiaozhu001** [comment]
钱包余额不在刷新
![image](https://user-images.githubusercontent.com/31197436/79682958-27d21100-8259-11ea-86df-69c5ace10ba3.png)

**Comment by yqrashawn** [comment]
> 由code 改为bytecode confluxJS.Contract({abi: abi,bytecode: code}); 正确使用

demo 页面没有更新适配新版钱包和 sdk, 后面会想办法做成自动更新.

**Comment by yqrashawn** [comment]
> 钱包余额不在刷新

目前 portal 的 balance 的确不会自动更新, 只会在初次打开/切换网络是更新

**Comment by xiaozhu001** [comment]
问题描述：我在进行给合约进行转1cfx后合约中拿到msg.value值，使用js-conflux-sdk获取的时候时正常得到 “1000000000000000000” 值，在钱包插件中获得到“[-1486618624, 232830643, sign: false]”，无法得到想要的值

**Comment by xiaozhu001** [comment]
@yqrashawn  上面的问题我已经大概知道原因了，可能是由于底层升级了，但是钱包插件未升级，导致的，目前js-conflux-sdk获取时需要使用这个util.unit.fromDripToCFX(ret).toString(10)方式转换

**Comment by xiaozhu001** [comment]
@yqrashawn 希望钱包插件可以提供一个接口，功能是指定金额的，这个金额不可修改，除非放弃本次交易，这样的一个功能，因为面对某些场景，需要让用户转指定的金额的操作，不希望用户转其他金额

**Comment by xiaozhu001** [comment]
@yqrashawn  我发现直接在使用钱包进行复制一些地址时，复制出来的地址，有些大写有些小写，继续转账功能时会出现失败，能否技术团队优化下，进行.toLocaleLowerCase()操作下.

**Comment by angelia-yuqi-personal** [comment]
> @yqrashawn  我发现直接在使用钱包进行复制一些地址时，复制出来的地址，有些大写有些小写，继续转账功能时会出现失败，能否技术团队优化下，进行.toLocaleLowerCase()操作下.

这个是插件钱包特殊的checksum机制，怕有人输错地址转错账，如果想要做dapp应用，可以自己在应用转小写，如果在钱包里用，基本都是支持checksum的
